

server:
  port: 7002
springdoc:
  swagger-ui:
    enabled: true  # Swagger UI? ???
    operations-sorter: method # Swagger UI?? API ???? ???? ??? ??? ???? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Spring_Chatting
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # sql ??? ??? ??

token:
  secret-key: "SECRET" # ?? ???? ?? ???
  refresh-secret-key: "REFRESH_SECRET" # ???? ?? ???? ?? ???
  token-time: 300 # ??? ????
  refresh-token-time: 300 # ???? ??? ????